# Generated by Django 5.2.1 on 2025-09-27 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='transformation',
            new_name='form',
        ),
        migrations.RemoveField(
            model_name='character',
            name='full_body_image_url',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='character',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/full_body/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='saga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='special_move',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ultimate_move',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
    ]
