# Generated by Django 5.2.1 on 2025-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_transformation_character_form_and_more'),
    ]

    operations = [
        # Rename level to card_level
        migrations.RenameField(
            model_name='character',
            old_name='level',
            new_name='card_level',
        ),
        # Remove health field
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        # Add speed field
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        # Add energy field
        migrations.AddField(
            model_name='character',
            name='energy',
            field=models.IntegerField(default=100),
        ),
    ]
