# Generated by Django 5.2.1 on 2025-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20250928_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gradient_direction',
            field=models.CharField(default='br', help_text='Gradient direction (to, br, bl, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary theme color (hex code, e.g., #3B82F6)', max_length=7),
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Secondary theme color (hex code, e.g., #1E40AF)', max_length=7),
        ),
    ]
