# Generated by Django 5.2.1 on 2025-09-27 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('battle_log', models.JSONField(blank=True, default=list)),
                ('battle_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_character1', to='characters.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_character2', to='characters.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victories', to='characters.character')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('damage_dealt', models.IntegerField(default=0)),
                ('defender_health_after', models.IntegerField()),
                ('turn_log', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='characters.character')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='battles.battle')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='characters.character')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
    ]
