# Generated by Django 5.2.1 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sage', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('image_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
