# Generated by Django 5.2.1 on 2025-07-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_delete_modelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sage',
            new_name='saga',
        ),
    ]
