# Generated by Django 5.2.1 on 2025-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_rename_defence_character_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.ImageField(upload_to='characters/'),
        ),
    ]
