# Generated by Django 5.2.1 on 2025-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='character',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
        migrations.AddField(
            model_name='character',
            name='attack_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='defense_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='energy_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='special_move',
            field=models.CharField(default='sepcial_move', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='speed_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strengths',
            field=models.CharField(default='strength', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(default='type', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='ultimate_move',
            field=models.CharField(default='ultimate_move', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.CharField(default='weakness', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(default='role', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='saga',
            field=models.CharField(default='saga', max_length=100),
        ),
    ]
