# Generated by Django 5.2.1 on 2025-07-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_character_attack_remove_character_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='form',
            field=models.CharField(default='form', max_length=100),
        ),
    ]
