# Generated by Django 5.2.1 on 2025-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='form', max_length=500),
        ),
    ]
