# Generated by Django 5.2.1 on 2025-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_character_form_alter_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
