# Generated by Django 5.2.1 on 2025-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_alter_character_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.AddField(
            model_name='character',
            name='image_full_body',
            field=models.ImageField(null=True, upload_to='characters/full_body'),
        ),
        migrations.AddField(
            model_name='character',
            name='image_profile',
            field=models.ImageField(null=True, upload_to='characters/profile'),
        ),
    ]
