# Generated by Django 5.2.1 on 2025-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_remove_character_image_url_character_image_full_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.CharField(default=0),
        ),
    ]
