# Generated by Django 5.2.1 on 2025-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_alter_character_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='special_move',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='strengths',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='ultimate_move',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weaknesses',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
