# Generated by Django 5.2.1 on 2025-07-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sage', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('image_url', models.ImageField(upload_to='')),
            ],
        ),
    ]
