# Generated by Django 5.2.1 on 2025-07-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_rename_sage_character_saga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='defence',
            new_name='defense',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Role',
            new_name='role',
        ),
    ]
